### ISSUE TITLE
Am I allowed to just add a link?

### ISSUE THREAD

**Issue by martiansideofthemoon** [saketkc/fos-proposals#11]
I just got accepted for GSoC  - 2016 with Mozilla. My proposal is not in a markdown format. Am I permitted to just add a link to the PDF?

**Comment by meetps** [comment]
You could use pandoc to convert a doc/html to markdown_github as suggested in the README. 
Even my proposal wasn't in markdown.

**Comment by saketkc** [comment]
Hi @martiansideofthemoon,  congrats for GSoC! My idea is to keep only markdowns since they are readily readable  (and are faster!). If you have a `doc` file, it should be fairly straight forward converting it to a markdown using the instructions on the README. If you have any questions regarding doc conversion, do let me know. Hope to see your proposal here!

**Comment by martiansideofthemoon** [comment]
Added it in #15 @saketkc . I hope it is okay.
@meetshah1995 , this worked for me https://domchristie.github.io/to-markdown/
